# # tye application configuration file
# # read all about it at https://github.com/dotnet/tye
# #
# # when you've given us a try, we'd love to know what you think:
# #    https://aka.ms/AA7q20u
# #
name: dnet5-grpc
# ingress:
#   - name: ingress
#     bindings:
#       - port: 8080
#     rules:
#       - path: /vote
#         service: voteweb
#       - path: /results
#         service: resultsweb
services:
- name: products-grpc
  project: src/Services/Products/Products.Grpc/Products.Grpc.csproj
- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2019-latest 
  env:
  - name: SA_PASSWORD
    value: "V0teM!cr0s3rv!ce"
  - name: ACCEPT_EULA
    value: 'Y'
  volumes:
  - name: vote-storage
    target: /var/opt/mssql
  bindings:
  - name: http # think this is the name needed for the port
    port: 1400
    containerPort: 1433
  - name: voteDb
    connectionString: Server=${host};User Id=sa;Database=VoteDB;Password=${env:SA_PASSWORD};
  - name: queueDb
    connectionString: Server=${host};User Id=sa;Database=VoteQueueDb;Password=${env:SA_PASSWORD};